syntax = "proto3";

package users;

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";

service UsersService {
    // rpc AddUser (AddUserRequest) returns (AddUserResponse);
    rpc GetUser (GetUserRequest) returns (GetUserResponse);
    // rpc UpdateUser (UpdateUserRequest) returns (UpdateUserResponse);
    // rpc DeleteUser (DeleteUserRequest) returns (DeleteUserResponse);
    // rpc RestoreUser (RestoreUserRequest) returns (RestoreUserResponse);
    // rpc HardDeleteUser (HardDeleteUserRequest) returns (google.protobuf.Empty);
}

message User {
    string id = 1;
    
    string email = 2;
    string display_name = 3;
    
    string password_hash = 4; 

    optional string first_name = 5;
    optional string last_name = 6;
    optional string avatar_url = 7;
    optional string phone = 8;
    optional string bio = 9;

    string user_role = 10; // customer, master, admin
    bool is_active = 11;    

    google.protobuf.Timestamp created_at = 12;
    optional google.protobuf.Timestamp edited_at = 13; 
    optional google.protobuf.Timestamp deleted_at = 14;  
    optional google.protobuf.Timestamp last_login_at = 15; 
}

message AddUserRequest {
    string email = 1;
    string display_name = 2;
    string password = 3;
    
    optional string first_name = 4;
    optional string last_name = 5;
    optional string avatar_url = 6;
    optional string phone = 7;
    optional string bio = 8;
    
    string user_role = 9; // По умолчанию на бэкенде ставим "customer"
}

message AddUserResponse {
    User user = 1;
}

message GetUserRequest {
    string id = 1;
}

message GetUserResponse {
    User user = 1;
}

message UpdateUserRequest {
    string id = 1; 
    
    optional string email = 2;
    optional string display_name = 3;
    optional string password = 4;
    optional bool is_active = 5;
    optional string first_name = 6;
    optional string last_name = 7;
    optional string avatar_url = 8;
    optional string phone = 9;
    optional string bio = 10;
    optional string user_role = 11;
}

message UpdateUserResponse {
    User user = 1;
}

message DeleteUserRequest {
    string id = 1;
    optional string reason = 2;
}

message DeleteUserResponse {
    string id = 1;
    bool success = 2;
    google.protobuf.Timestamp deleted_at = 3;
}

message RestoreUserRequest {
    string id = 1;
}

message RestoreUserResponse {
    User user = 1;
}

message HardDeleteUserRequest {
    string id = 1;
}
