
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import:ro
    networks:
      - internal_network

  gateway:
    image: nginx:1.27
    restart: unless-stopped
    container_name: gateway
    ports:
      - "8080:80"
    networks:
      - internal_network
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro

  backend:
    build:
      context: ./backend
      # dockerfile: Dockerfile.prod
      dockerfile: Dockerfile.dev
    container_name: backend
    expose:
      - "50051"
    environment:
      - EXPOSED_ADDR=0.0.0.0:50051
      - KEYCLOAK_ISSUER=http://keycloak:8080/realms/sample
      - KEYCLOAK_AUDIENCE=sample-api
    restart: unless-stopped
    networks:
      - internal_network
      
networks:
  internal_network:
    driver: bridge
