events {
    worker_connections 1024;
}

http {
    # Используем стандартный, гарантированно рабочий формат логов Nginx
    access_log /var/log/nginx/access.log;

    upstream core_backend {
        # Имя хоста "core" соответствует названию сервиса в docker-compose.yml
        server core:50051;
    }

    server {
        listen 8080;
        http2 on; # Включаем HTTP/2 (Nginx 1.25+)

        server_name localhost;

        location /messenger.MessengerCoreService/ {
            grpc_pass grpc://core_backend;
            
            # Настройка таймаутов, чтобы прокси не рвал постоянные стримы мессенджера
            grpc_read_timeout 86400s;
            grpc_send_timeout 86400s;
        }

        location / {
            return 404;
        }
    }
}
