events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        http2 on;

        server_name localhost;

        location /gateway_health {
            return 200 "gateway_health";
        }

        location /api/backend/ {
            proxy_pass http://backend:50051/;
        }

        location / {
            return 404;
        }  
    }
}