events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        http2 on;

        server_name localhost;

        location /gateway_health {
            return 200 "gateway_health";
        } 

        location / {
            return 404;
        }  
    }
}