syntax = "proto3";

package projects;

service ProjectsService {
    rpc CreateProject (CreateProjectRequest) returns (CreateProjectResponse);
    rpc GetProject (GetProjectRequest) returns (GetProjectResponse);
    rpc UpdateProject (UpdateProjectRequest) returns (UpdateProjectResponse);
    // rpc DeleteProject (DeleteProjectRequest) returns (DeleteProjectResponse);
    // rpc RestoreProject (RestoreProjectRequest) returns (RestoreProjectResponse);
    // rpc HardDeleteProject (HardDeleteProjectRequest) returns (HardDeleteProjectResponse);
}

message Project {
    string id = 1;
    string owner_id = 2;

    string title = 3;
    optional string description = 4;

    repeated string team_members = 5;

    int64 created_at = 6;
    optional int64 deadline = 7;

    optional int64 edited_at = 8; 
    optional int64 deleted_at = 9;  

    string status = 10;
}

message CreateProjectRequest {
    string owner_id = 1;

    string title = 2;
    optional string description = 3;

    repeated string team_members = 4;

    optional int64 deadline = 5;

    string status = 6;
}

message CreateProjectResponse {
    Project project = 1;
}

message GetProjectRequest {
    string id = 1;
}

message GetProjectResponse {
    Project project = 1;
}

message UpdateProjectRequest {
    string id = 1; 
    
    optional string owner_id = 2;
    optional string title = 3;
    optional string description = 4;
    optional int64 deadline = 5;
    optional string status = 6;
}

message UpdateProjectResponse {
    Project project = 1;
}

// message DeleteProjectRequest {
//     string id = 1;
//     optional string reason = 2;
// }

// message DeleteProjectResponse {
//     string id = 1;
//     bool success = 2;
//     int64 deleted_at = 3;
// }

// message RestoreProjectRequest {
//     string id = 1;
// }

// message RestoreProjectResponse {
//     Project project = 1;
// }

// message HardDeleteProjectRequest {
//     string id = 1;
// }

// message HardDeleteProjectResponse {
//     string id = 1;
//     bool success = 2;
// }